#!/bin/sh

#
# This script generates example main()'s for the LFSR library
# Takes one argument: the number of bits in the LFSR
#
# Written by Alex Weber
# All code in this project is public domain
#

cat <<EOF > ${1}bit.c
#include <stdio.h>
#include "lfsr.h"

// ${1}-bit main program for the LFSR library
// automatically generated by generate_main.sh
int main()
{
  enum lfsr_bit_t state[${1}];
  lfsr_load(state, ${1}, 1);
  size_t taps[] = LFSR_MAXIMAL${1};
  while (1) {
    printf("%u\n", lfsr_dump(state, ${1}));
    lfsr_shift(state, ${1}, lfsr_xor_taps(state, ${1}, taps, sizeof(taps) / sizeof(size_t)));
  }
}
EOF
